[project]
name = "vtx-plugin-auth-basic"
language = "rust"
authors = [{ name = "VTX Team", email = "" }]
description = "Basic auth plugin for VTX"
license = "MIT"
homepage = "https://github.com/Vtxdeo/vtx-plugin-auth-basic"
repository = "https://github.com/Vtxdeo/vtx-plugin-auth-basic"
keywords = ["VTX Team", "plugin", "auth"]
